# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: confluent/meta.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'confluent/meta.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


try:
    DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x63onfluent/meta.proto\x12\tconfluent\x1a google/protobuf/descriptor.proto\"}\n\x04Meta\x12\x0b\n\x03\x64oc\x18\x01 \x01(\t\x12+\n\x06params\x18\x02 \x03(\x0b\x32\x1b.confluent.Meta.ParamsEntry\x12\x0c\n\x04tags\x18\x03 \x03(\t\x1a-\n\x0bParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01:A\n\tfile_meta\x12\x1c.google.protobuf.FileOptions\x18\xa7\x08 \x01(\x0b\x32\x0f.confluent.Meta:G\n\x0cmessage_meta\x12\x1f.google.protobuf.MessageOptions\x18\xa8\x08 \x01(\x0b\x32\x0f.confluent.Meta:C\n\nfield_meta\x12\x1d.google.protobuf.FieldOptions\x18\xa9\x08 \x01(\x0b\x32\x0f.confluent.MetaB2\n*io.confluent.kafka.schemaregistry.protobufB\x04Metab\x06proto3')
except TypeError:  # already registered (e.g. by confluent_kafka)
    DESCRIPTOR = _descriptor_pool.Default().FindFileByName('confluent/meta.proto')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'confluent.meta_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n*io.confluent.kafka.schemaregistry.protobufB\004Meta'
  _globals['_META_PARAMSENTRY']._loaded_options = None
  _globals['_META_PARAMSENTRY']._serialized_options = b'8\001'
  _globals['_META']._serialized_start=69
  _globals['_META']._serialized_end=194
  _globals['_META_PARAMSENTRY']._serialized_start=149
  _globals['_META_PARAMSENTRY']._serialized_end=194
# @@protoc_insertion_point(module_scope)
