# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: AllTypes.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'AllTypes.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Customer_pb2 as Customer__pb2
import Product_pb2 as Product__pb2
import Order_pb2 as Order__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x41llTypes.proto\x12\x1bio.confluent.examples.proto\x1a\x0e\x43ustomer.proto\x1a\rProduct.proto\x1a\x0bOrder.proto\"\xc1\x01\n\x08\x41llTypes\x12\x39\n\x08\x63ustomer\x18\x01 \x01(\x0b\x32%.io.confluent.examples.proto.CustomerH\x00\x12\x37\n\x07product\x18\x02 \x01(\x0b\x32$.io.confluent.examples.proto.ProductH\x00\x12\x33\n\x05order\x18\x03 \x01(\x0b\x32\".io.confluent.examples.proto.OrderH\x00\x42\x0c\n\noneof_typeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AllTypes_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ALLTYPES']._serialized_start=92
  _globals['_ALLTYPES']._serialized_end=285
# @@protoc_insertion_point(module_scope)
