# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: MyRecord.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'MyRecord.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import other_pb2 as other__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eMyRecord.proto\x12\x08\x63om.acme\x1a\x0bother.proto\"9\n\x08MyRecord\x12\n\n\x02\x66\x31\x18\x01 \x01(\t\x12!\n\x02\x66\x32\x18\x02 \x01(\x0b\x32\x15.com.acme.OtherRecordb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MyRecord_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MYRECORD']._serialized_start=41
  _globals['_MYRECORD']._serialized_end=98
# @@protoc_insertion_point(module_scope)
