# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: User.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'User.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from confluent import meta_pb2 as confluent_dot_meta__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nUser.proto\x1a\x14\x63onfluent/meta.proto\"9\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x16\n\x04name\x18\x02 \x01(\tB\x08\xca\x42\x05\x1a\x03PII\x12\r\n\x05\x65mail\x18\x03 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'User_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER'].fields_by_name['name']._loaded_options = None
  _globals['_USER'].fields_by_name['name']._serialized_options = b'\312B\005\032\003PII'
  _globals['_USER']._serialized_start=36
  _globals['_USER']._serialized_end=93
# @@protoc_insertion_point(module_scope)
